version: '3'
services:
  spring_boot_registration:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: spring_boot_registration
    image: spring_boot_registration
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev